### ISSUE TITLE
GPL or Lesser GPL?

### ISSUE THREAD

**Issue by jjYBdx4IL** [sjoerdvankreel/xt-audio#1]
Please clarify, there are two licenses at the root of the project.

TY!

**Comment by sjoerdvankreel** [comment]
It's LGPL. Actually in order to license under lgpl you must include both
licenses, see https://www.gnu.org/licenses/gpl-howto.html.

"If you are releasing your program under the LGPL, you should also include the
text version of the LGPL <https://www.gnu.org/licenses/lgpl.txt>, usually
in a file called COPYING.LESSER. Please note that, since the LGPL is a set
of additional permissions on top of the GPL, it's important to include both
licenses so users have all the materials they need to understand their
rights."

2017-04-30 0:46 GMT+02:00 jjYBdx4IL <notifications@github.com>:

**Comment by jjYBdx4IL** [comment]
oh ok, ty. I was irritated by github.com's display of the repository as GPL3 in the upper right corner of https://github.com/sjoerdvankreel/xt-audio . And a lot of source code files don't have license headers like it is usually done.,
