### ISSUE TITLE
.so and .dll requirement

### ISSUE THREAD

**Issue by jameshball** [sjoerdvankreel/xt-audio#10]
In previous versions of xt-audio, there were different library folders for different platforms (e.g. linux-x64 and win32-x64 etc.). I was wondering whether these libraries were still required? Audio output seems to still work fine when these folders have been deleted (and I don't get any errors like I did before when not including libraries), but there are still some libraries in the latest binaries for 1.9, so I just wanted to check.

Also, is there any extra configuration required for MacOS, or are the linux .so files fine?

**Comment by jameshball** [comment]
I should clarify, this is using the Java version of the library. If you need any more information about my setup then you can have a look at my repo :) https://github.com/jameshball/osci-render

**Comment by sjoerdvankreel** [comment]
Hey, since 1.8 all native libraries are packed into the jar. You don't need those folders anymore, just pull in xtaudio from mvn central and you're good to go. Regarding MacOs, it's not supported. As far as I know, ALSA is exclusive to linux. It may be possible to get JACK and PulseAudio running on mac, but i've never implemented it. But any decent Mac backend should support CoreAudio, otherwise it'd be like windows without wasapi or linux without alsa, which is kinda the purpose of xtaudio, providing the most direct-to-hardware option on the platform available. Anyway i don't have a mac and not enough spare time on my hands to implement a new backend from scratch, so contributions are welcome! You've done it before, after all ;) Btw i wanted to check what your project's about but the youtube links in the README are dead ?

**Comment by jameshball** [comment]
Brilliant! I've removed them now :) much more convenient.

That's a shame there's no mac version but I completely understand, given I'm in the same situation right now with osci-render trying to port it to MacOS which is turning out to be a bit of a pain!

Not sure why the youtube links are dead, this should work: https://www.youtube.com/watch?v=feQzC_Tz5K4

**Comment by jameshball** [comment]
Whilst this issue is open, I should also ask about the easiest way I can also save the audio data I'm passing to xt-audio to an audio file? Not sure if that's part of the library or whether I'll have to directly save to a .wav file or something, but I'm sure you're more knowledgeable than I am.

Ideally, I'd write to a file as I'm writing to the output buffer in the render function: https://github.com/jameshball/osci-render/blob/master/src/main/java/sh/ball/audio/AudioPlayer.java#L48 Any ideas about the most relevant file format or anything would be helpful :)

**Comment by sjoerdvankreel** [comment]
Cool stuff! Is that a 3d rendering of an actual audio signal?

Problem with MacOS is i've never been able to get my hands on a free/developer version (does it even exist?).

About saving to file, there's no such facility in xtaudio. The easiest way is to just dump everything you feed to xtaudio in a binary raw pcm audio file (.RAW). Raw audio files are literally just a dump of the in-memory audio stream and can be opened using audio editing software such as Audacity (of course you'd have to tell it the format of the file, since there's no metadata). If you want to get fancy, pcm formats such as .WAV or .AU are also reasonable easy to implement by hand, they are basically just a fixed size header containing the metadata (i.e. audio format) followed by a dump of the raw data. There are probably libraries for these but should be easy enough to do by hand. Anything beyond that (think compressed formats such as ogg or mp3) you definitely want a library for that. 

That being said, if you care about your audio stream being glitch-free and with tolerable latency, never ever actually do I/O (i.e. write to file) in the audio thread. Submit audio packets to a lock-free queue instead, and write to file on a low prio background thread. This http://www.rossbencina.com/code/real-time-audio-programming-101-time-waits-for-nothing post by (one of the?) creators of portaudio explains it better than i ever could.

**Comment by jameshball** [comment]
It is yes, the left audio channel volume is the X value on the display and right audio channel volume is Y. If you fluctuate that very quickly you can render whatever you want :)

That is extremely helpful thank you! I'll have to experiment with the audio file stuff - what you've said about a separate thread is so obvious now you've said it but I had not considered that before.

**Comment by sjoerdvankreel** [comment]
Love it! What about screen Z though? Is it solely derived from the camera position?

**Comment by sjoerdvankreel** [comment]
Also that seems like really low frequency audio. What does it sound like? Guess some sort of rumble?

**Comment by jameshball** [comment]
Z position isn't needed because, as you said, it's just a camera view of the object so the 3D coordinates are projected into 2D.

Did you listen to the audio on the YouTube video? Past the intro all the objects have their sound too :) they're all very 'normal' sounds and don't really have any repeating characteristics - each thing I'm rendering has a very different sound.

If you have a look on YouTube for oscilloscope music, there's loads of very good examples of doing a similar thing with audio which is a lot of fun :)

**Comment by jameshball** [comment]
The frequency of the audio corresponds to how quickly the object is being drawn - so if I draw the objects slowly, the frequency will be low.

I'm drawing to the screen very quickly to get lots of frames drawn (to achieve a high frame rate) which means the frequency is actually quite high.

**Comment by sjoerdvankreel** [comment]
Ah yes i hear now. It takes on all kinds of frequencies according to combined parameter input right? I especially like the first one, the cube. Sounds a bit like oldskool analog synthesis. Really nice combo of 3d graphics and audio DSP you've got there! The bit crush actually sounds not unlike some audio bitcrush vsts i've heard.

**Comment by jameshball** [comment]
Yeah exactly, the frequencies completely depend on the object I'm displaying along with all the parameters I've chosen. I'm glad the bitcrush sounds 'accurate' because I just thought of the idea and didn't really base it off of any other existing bit crush :)


Glad you like it! It's made possible by xt-audio because it 'just works' and was very easy to get set up, so thank you!

**Comment by sjoerdvankreel** [comment]
Good to hear, and good luck with the project!
