### ISSUE TITLE
[Question] How to record audio on Linux

### ISSUE THREAD

**Issue by sblantipodi** [sjoerdvankreel/xt-audio#12]
Hi,
I'm using something like this to capture audio on Windows.
This snippet uses the loopback devices to record the audio.

```
package com.mycompany.mavenproject1;

import com.sun.jna.Pointer;
import java.util.EnumSet;
import xt.audio.*;
import xt.audio.Enums.*;
import xt.audio.Structs.*;

public class NewClass {

    static int onBuffer(XtStream stream, XtBuffer buffer, Object o) throws Exception {
        XtSafeBuffer safe = XtSafeBuffer.get(stream);
        safe.lock(buffer);
        float[] samples = (float[]) safe.getInput();
        for (int i = 0; i < buffer.frames; i++) {
            float left = samples[i * 2];
            float right = samples[i * 2 + 1];
            // YOUR CODE HERE
        }
        safe.unlock(buffer);
        return 0;
    }

    public static void main(String[] args) throws Exception {
        try (XtPlatform platform = XtAudio.init("demo", Pointer.NULL)) {
            XtService service = platform.getService(XtSystem.WASAPI);
            try (XtDeviceList list = service.openDeviceList(EnumSet.of(XtEnumFlags.INPUT))) {
                for (int d = 0; d < list.getCount(); d++) {
                    String id = list.getId(d);
                    EnumSet<XtDeviceCaps> caps = list.getCapabilities(id);
                    if (caps.contains(XtDeviceCaps.LOOPBACK)) {
                        try (XtDevice device = service.openDevice(id)) {
                            XtStreamParams streamParams = new XtStreamParams(true, NewClass::onBuffer, null, null);
                            XtFormat format = new XtFormat(new XtMix(48000, XtSample.FLOAT32), new XtChannels(2, 0, 0, 0));
                            XtBufferSize buffer = device.getBufferSize(format);
                            XtDeviceStreamParams deviceParams = new XtDeviceStreamParams(streamParams, format, buffer.current);
                            try (XtStream stream = device.openStream(deviceParams, null);
                                    XtSafeBuffer safe = XtSafeBuffer.register(stream, true)) {
                                stream.start();
                                Thread.sleep(1000);
                                stream.stop();
                            }
                        }
                    }
                }
            }
        } catch (XtException e) {
            System.out.println(XtAudio.getErrorInfo(e.getError()));
        }
    }
}
```

On my linux boxes it seems that there is no loopback audio devices, how can I do the same thing on Linux?
Is there someone who can give me some tips please?

Thanks
Davide

**Comment by sjoerdvankreel** [comment]
Hey again!
Unfortunately none of the linux backends provide explicit support for loopback recording, like it's done with WASAPI.

That being said, it should be possible although it may not be easy, and i've never tried it myself. The simplest solution would be to use the JACK backend, using the jack control panel you can route anything to anything. That does imply that the thing you want to record from uses JACK also, though, and PulseAudio seems to be the default these days. 

Then there's this thing called pulseaudio-module-jack which in theory allows pulseaudio and jack to interoperate, but i never got it to work reliably. See here https://askubuntu.com/questions/572120/how-to-use-jack-and-pulseaudio-alsa-at-the-same-time-on-the-same-audio-device and here https://linuxmusicians.com/viewtopic.php?t=20458. 

If you want to stick to PulseAudio, apparently you can record from so-called Monitor devices as described here: https://manual.audacityteam.org/man/tutorial_recording_computer_playback_on_linux.html. 

And finally if you're using plain ALSA and your linux config file-fu is up for it, something like this: https://bbs.archlinux.org/viewtopic.php?id=251591 might work. 

All being said, to be quite frank i never ever once got all of JACK + PulseAudio + ALSA working reliably on the same machine, it's always JACK over ALSA, Pulse over ALSA, or just plain ALSA (i even set up dual boots for these configurations to test XtAudio). See also here https://linuxmusicians.com/viewtopic.php?t=20458. 

Anyway, loopback recording on linux should be entirely possible, provided you have the patience to install necessary packages and tweak config files untill you get it right (at least that's my experience with linux audio). Alternatively, how about getting yourself a basic cheap soundcard with hardware loopback? If hardware loopback is available, that's what wasapi uses also (otherwise it's emulated).

**Comment by sblantipodi** [comment]
@sjoerdvankreel many thanks for the kind answer, I really appreciate it.

I'm developing a software meant for everyone, it's difficult to buy everyone a soundcard with hardware loopback but it's easy to recommend them how to create a software loopback by installing the required packages 😄 

I think that installing packages to create a software loopback is the best bet for me and XT Audio works pretty well once done.

I really hope that you will continue to support and maintain this wonderful lib, thank you for your work and for your support.

Closing the issue.
