### ISSUE TITLE
Fails to init in .net5

### ISSUE THREAD

**Issue by skittleson** [sjoerdvankreel/xt-audio#16]
Attempting `using XtPlatform platform = XtAudio.Init(null, IntPtr.Zero); `

Results in:

 `PlatformWin32.cpp:37: in function Init: SUCCEEDED(CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED))`

**Comment by sjoerdvankreel** [comment]
Just in case anyone else stumbles into this, console-app [STAThread] async Main() isn't going to work with xt-audio. XtAudio.Init designates the calling thread as the "main" thread from which all calls into the xt-audio api should be made (with the exception of the audio buffer callback of course). This is done because it greatly simplifies xt-audio backend implementations which have varying requirements with respect to threading behaviour.

See for example Wasapi's AudioClient documentation here: https://docs.microsoft.com/en-us/windows/win32/api/audioclient/nf-audioclient-iaudioclient-initialize which states "Note  In Windows 8, the first use of IAudioClient to access the audio device should be on the STA thread. Calls from an MTA thread may result in undefined behavior.". 

Of course the constraint of having a single dedicated thread communicate with the xt-audio API is fundamentally at odds with async/await behaviour in the default synchronization context which posts to the threadpool. You should be ok with winforms or wpf synchronization context though which will resume on the ui thread.

Or TL;DR: async/await and thread affinity don't mix.

**Comment by realvictorprm** [comment]
Many thanks for the insight, was already wondering why one needs the attribute 😄
