### ISSUE TITLE
[Not a bug] Any plans of supporting macOS in the future?

### ISSUE THREAD

**Issue by notshriram** [sjoerdvankreel/xt-audio#21]
I think this is one of the best looking audio libraries I've ever seen. The only thing that other libraries have over this is macOS CoreAudio support. I was wondering if there are any plans to support this in the future.

**Comment by sjoerdvankreel** [comment]
Thanks! And sorry to say, but probably no, not ever. The primary reason being: money. Because this thing being low-latency, I need actual hardware to test on. A VM just don't cut it, there's no way to see if my code is 3-millisecond-buffer proof on a VM (expected latency is more like couple hundred ms). No problem for Windows, that's my development environment. Also no problem for Linux, just find a free ubuntu or whatever and set up a dual-boot. But i've never found a free OSX version for testing purposes, and if there ever was one, I bet it's gonna be a VM.

**Comment by slendidev** [comment]
I wish to try and add support, I have a macbook and can test

**Comment by sjoerdvankreel** [comment]
@xslendix Coincidentally i got hold of a macbook myself recently.
I'm not sure what you are proposing though - you write CoreAudio support, or I write it ?

**Comment by slendidev** [comment]
@sjoerdvankreel I wanna try and do it, sounds like a fun learning experience :^)

**Comment by sjoerdvankreel** [comment]
Cool! I wasn't too keen on doing it myself anyway.
That being said, now that I have a macbook, I can support you every step of the way by reviewing and testing.

How about something like this:
* You fork the repo, give me write access to the new one (or I just set up a new one and give you access)
* I do all the "stuff" except for writing the actual code, like:
* Put a skeleton mac version in place (function stubs etc)
* Update the build scripts, test scripts, documentation etc
* You code up the actual implementation?

Be aware that the code base currently compiles using MSVC and GCC only, X86/X64 only.
There might be some issues porting to CLang and ARM.

**Comment by slendidev** [comment]
LGTM making the fork rn

**Comment by slendidev** [comment]
@sjoerdvankreel fork made, gave you a collaboration invite

**Comment by sjoerdvankreel** [comment]
Great! Really appreciate you wanting to help out, too.
I'll probably need around a week or so to get stuff set up for you.

Meanwhile, here's some stuff to figure out in the meantime, I'm hoping you can do it:

* Is CoreAudio direct-to-hardware (like ASIO, ALSA:HW), or does it have a system mixer between the app and the hardware (like DirectSound, ALSA:Plug, PulseAudio), or does it support both (like WASAPI - shared/exclusive)?
* If it's 1 of those, stuff's easy, and you just need to tweak a few XtDeviceCaps flags.
* If it's both -- it's up to you, to support either mode or both. For WASAPI, the AudioService actually lists each device 2 or 3 times - once in "software" mode, once in "hardware" mode, and if applicable once in "loopback" mode.
* So probably we should find out, if CoreAudio supports software loopback, too.
* Is CoreAudio callback-based (like JACK, ASIO) or push/blocking-based (WASAPI, DirectSound, ALSA, Pulse)? (i.e., xt-audio gets called by CoreAudio to process the audio buffers, or, xt-audio calls upon CoreAudio to process the audio buffers. I vaguely recall that it is callback-based, but, not sure)
* In the case its blocking-based, we can do stream-aggregation. Otherwise not.
* Does CoreAudio have any kind of thread scheduling API, f.e. like WASAPI's "Audio" / "ProAudio" MMCSS features

For later, but still important:
* We should release universal binaries so not plain x64/arm
* I have zero clue about the status of java and .net on Mac. Guess .net core should work, but, never tried

**Comment by sjoerdvankreel** [comment]
@xslendix 

Also, how do you wanna go about this ?
Maybe feature-branch for each "significant" step like the initial skeleton, and then the device info, then the actual streaming etc?
I've never done any open-source collaboration, so, really i have no clue.

Also I'm closing this ticket so we won't keep bothering [notshriram](https://github.com/notshriram).
We can use https://github.com/sjoerdvankreel/xt-audio/issues/28 for further discussion.

**Comment by slendidev** [comment]
Yeah putting eveyrhing on its own branch sounds good, then we can merge into main branch @sjoerdvankreel
