### ISSUE TITLE
ASIO supported format detection

### ISSUE THREAD

**Issue by davidgiga1993** [sjoerdvankreel/xt-audio#4]
`device.supportsFormat` may return `false`, although the format is supported by the device.

# Configuration
- OS: Windows 10
- Device: Saffire Pro 24
- OS default audio device: Saffire Pro 24
- OS device config: 44.1kHz, 24bit

# Steps to reproduce
Iterate over every possible device configuration and call `supportsFormat`.
It will only return `true` for the samplerate which is used by the OS for the device.
This is wrong as ASIO is completely independent from the regular OS audio device.
Also it only returns 32 bit as audio format, although the device can only handle 24 bit.

I also used jasiohost which reported the correct configurations, regardless of the OS audio device configuration.

Output from xt-audio:
```
ASIO Saffire
Inputs:	Unit 1 IP 1
	Unit 1 IP 2
	Unit 1 IP 3
	Unit 1 IP 4
	Unit 1 SPDIF L
	Unit 1 SPDIF R
	Unit 1 ADAT 1
	Unit 1 ADAT 2
	Unit 1 ADAT 3
	Unit 1 ADAT 4
	Unit 1 ADAT 5
	Unit 1 ADAT 6
	Unit 1 ADAT 7
	Unit 1 ADAT 8
	Unit 1 Loop 1
	Unit 1 Loop 2
Format:
	1Ch 44100Hz 32Bit
	2Ch 44100Hz 32Bit
	3Ch 44100Hz 32Bit
	4Ch 44100Hz 32Bit
	5Ch 44100Hz 32Bit
	6Ch 44100Hz 32Bit
	7Ch 44100Hz 32Bit
	8Ch 44100Hz 32Bit
	9Ch 44100Hz 32Bit
	10Ch 44100Hz 32Bit
	11Ch 44100Hz 32Bit
	12Ch 44100Hz 32Bit
	13Ch 44100Hz 32Bit
	14Ch 44100Hz 32Bit
	15Ch 44100Hz 32Bit
	16Ch 44100Hz 32Bit
```

Output from jasiohost:
```
ASIO Saffire
Inputs:	Unit 1 IP 1
	Unit 1 IP 2
	Unit 1 IP 3
	Unit 1 IP 4
	Unit 1 SPDIF L
	Unit 1 SPDIF R
	Unit 1 ADAT 1
	Unit 1 ADAT 2
	Unit 1 ADAT 3
	Unit 1 ADAT 4
	Unit 1 ADAT 5
	Unit 1 ADAT 6
	Unit 1 ADAT 7
	Unit 1 ADAT 8
	Unit 1 Loop 1
	Unit 1 Loop 2
Format:
	1Ch 44100Hz 24Bit
	1Ch 48000Hz 24Bit
	1Ch 88200Hz 24Bit
	1Ch 96000Hz 24Bit
	2Ch 44100Hz 24Bit
	2Ch 48000Hz 24Bit
	2Ch 88200Hz 24Bit
	2Ch 96000Hz 24Bit
....
```

**Comment by sjoerdvankreel** [comment]
The ASIO backend for xt-audio will only report a format as supported when that format matches the format selected in the ASIO control panel. This is by design, the same goes for WASAPI shared mode (only the mix format selected in windows control panel reports as supported) and the JACK backend (only the sample rate of the JACK server is supported). This is mostly done because of interface consistency: unlike ASIO, WASAPI does not support a "set current samplerate" method. 

However, your assertion that "it will only return true for the samplerate which is used by the OS for the device" is false: the selected sample rate in the windows control panel should not affect the outcome of isFormatSupported in ASIO mode, only the selected format in the ASIO control panel should do that. Do you by any chance have the same sample rate selected in both the ASIO control panel and the windows control panel for that device? If so, please verify that changing the format in the ASIO control panel DOES affect the outcome of isFormatSupported, and changing the format in the windows control panel DOES NOT affect the outcome of isFormatSupported. If this is not the case, you may have found a bug. Just to be sure, you do use the Saffire device in ASIO mode from xt-audio (e.g. GetServiceBySetup(ProAudio) or GetServiceBySystem(Asio)), instead of accessing the device through it's WASAPI interface?

About the 24/32 bit distinction, this may have to do with the asio driver using the extended sample format (1 32 bit word used to represent a single 24 bit sample) instead of the packed format (3 bytes used to represent a single 24 bit sample), although in that case i'd expect jasiohost to report 32-bits also. Can you show the source code you used to obtain the above values and also the settings in your asio control panel?

**Comment by sjoerdvankreel** [comment]
Closing this because no response.
