### ISSUE TITLE
How do I change the sample rate in the selected device?

### ISSUE THREAD

**Issue by Vado101** [sjoerdvankreel/xt-audio#9]
I have a 24bit / 192kHz sound card that works over ASIO. How can I control the sampling rate and the number of bits in my application using the xt-audio library?

**Comment by sjoerdvankreel** [comment]
You can't, at least not directly. XT-Audio will only list the driver's current sample rate as "supported", meaning the user will have to select the desired sample rate manually in the ASIO control panel. You can use XtDevice.ShowControlPanel to pop up the control panel for the ASIO device. As for the bit depth, ASIO drivers are typically fixed at 32-bit integer and convert to 24-bit on the fly, but if your card/driver really exposes 24-bit packed sample to the application than it should just work out of the box. (As a side note, the ASIO API actually supports a SetCurrentSampleRate() function, but it is not exposed by XTAudio because none of the other backends provide similar functionality).

**Comment by Vado101** [comment]
Thanks for the answer! Please tell me in what format is the data from the sound card (ASIO) recorded when using the library xt-audio? PCM?

**Comment by sjoerdvankreel** [comment]
It's always PCM. You can only select the channel count, bit depth and sample rate when opening a stream, provided the format you select is supported by the device. See https://sjoerdvankreel.github.io/xt-audio/doc/core/html/struct_xt_format.html.

**Comment by Vado101** [comment]
I am using xt-audio from Java. What byte order will I receive: big-endian or little-endian? Is it always the same?

**Comment by sjoerdvankreel** [comment]
Always little endian and most likely ASIOSTInt32LSB, which maps to XtSampleInt32.

**Comment by sjoerdvankreel** [comment]
Actually ASIO uses LSB/MSB for "least/most significant byte" but come to think about it I'm not sure if that's the same as little/big endian. Anyway, 0xFF000000 is loud and 0x000000FF is near silence, as it should be.

**Comment by Vado101** [comment]
Thank you for your help!
